# This action checks that certain groups of specs have matching tags.
# The main use case is to ensure that signed specs have the same Version and
#   Release tags as their unsigned counterparts
name: Spec Entanglement Mismatch Check

on:
  push:
    branches: [main, dev, 1.0*]
  pull_request:
    branches: [main, dev, 1.0*]

jobs:
  check:
    name: Spec Entanglement Mismatch Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the branch of our repo that triggered this action
      - name: Workflow trigger checkout
        uses: actions/checkout@v2

      # For consistency, we use the same major/minor version of Python that CBL-Mariner ships
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Get Python dependencies
        run: python3 -m pip install python-rpm-spec

      - name: Run entanglement checking script
        run: python3 ./.github/workflows/check_entangled_specs.py .
