# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# Workflow to automatedly verify the quickstart instructions

name: Verify Quickstart 1.0

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  get_input-srpms:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: '1.0-stable'

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Install Remaining Prerequisites
      run: |
        # Golang and docker are already installed on the agent
        sudo apt-get update
        sudo apt -y install make tar wget curl rpm qemu-utils genisoimage pigz parted

    - name: Download SRPMS
      run: |
        pushd toolkit
        sudo make go-tools REBUILD_TOOLS=y
        sudo make input-srpms DOWNLOAD_SRPMS=y
        popd

  iso_quickstart:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: '1.0-stable'

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Install Remaining Prerequisites
      run: |
        # Golang and docker are already installed on the agent
        sudo apt-get update
        sudo apt -y install make tar wget curl rpm qemu-utils genisoimage pigz parted

    - name: ISO Quick Start
      run: |
        pushd toolkit
        sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
        popd

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CBL-Mariner-ISO
          path: |
            ./out/images/full/*.*

  vhdx_quickstart:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: '1.0-stable'

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Install Remaining Prerequisites
      run: |
        # Golang and docker are already installed on the agent
        sudo apt-get update
        sudo apt -y install make tar wget curl rpm qemu-utils genisoimage pigz parted

    - name: VHDX Quick Start
      run: |
        pushd toolkit
        sudo make image REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
        popd

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CBL-Mariner vhdx
          path: |
            ./out/images/full/*.*
